In [2]:
import numpy as np
import pandas as pd
fullData = pd.read_csv('data/churn_train.csv')
fullData.head()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct
0,6.94,5.0,5.0,1.00,Astapor,2014-05-03,Android,2014-01-12,0.0,0,False,100.0
1,8.06,5.0,5.0,1.00,Astapor,2014-01-26,Android,2014-01-25,0.0,2,True,0.0
2,21.50,4.0,NaN,1.00,Winterfell,2014-05-21,iPhone,2014-01-02,0.0,1,True,100.0
3,9.46,5.0,NaN,2.75,Winterfell,2014-01-10,Android,2014-01-09,100.0,1,False,100.0
4,13.77,5.0,NaN,1.00,Winterfell,2014-05-13,iPhone,2014-01-31,0.0,0,False,100.0

In [3]:
fullData['last_trip_date'] = pd.to_datetime(fullData['last_trip_date'])
condition = fullData['last_trip_date'] < '2014-06-01'
fullData['churn'] = 1
fullData.ix[~condition, 'churn'] = 0
fullData.head(20)

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct,churn
0,6.94,5.0,5.0,1.00,Astapor,2014-05-03,Android,2014-01-12,0.0,0,False,100.0,1
1,8.06,5.0,5.0,1.00,Astapor,2014-01-26,Android,2014-01-25,0.0,2,True,0.0,1
2,21.50,4.0,NaN,1.00,Winterfell,2014-05-21,iPhone,2014-01-02,0.0,1,True,100.0,1
3,9.46,5.0,NaN,2.75,Winterfell,2014-01-10,Android,2014-01-09,100.0,1,False,100.0,1
4,13.77,5.0,NaN,1.00,Winterfell,2014-05-13,iPhone,2014-01-31,0.0,0,False,100.0,1
5,14.51,5.0,NaN,1.00,Astapor,2014-04-22,iPhone,2014-01-29,0.0,0,True,100.0,1
6,4.87,4.7,4.0,1.00,Astapor,2014-04-21,Android,2014-01-18,0.0,0,False,66.7,1
7,1.78,4.0,5.0,1.00,Winterfell,2014-01-12,iPhone,2014-01-11,0.0,3,False,0.0,1
8,6.87,5.0,4.7,1.00,Astapor,2014-01-30,Android,2014-01-01,0.0,3,False,66.7,1
9,2.41,5.0,3.0,1.00,Winterfell,2014-01-29,iPhone,2014-01-28,0.0,1,False,100.0,1
10,3.96,5.0,NaN,2.00,Winterfell,2014-01-19,iPhone,2014-01-18,100.0,1,False,0.0,1
11,17.04,5.0,NaN,1.00,Winterfell,2014-05-12,Android,2014-01-26,0.0,0,True,100.0,1
12,5.42,4.7,5.0,1.00,Astapor,2014-06-28,iPhone,2014-01-05,0.0,2,True,33.3,0
13,5.02,5.0,5.0,1.00,Astapor,2014-01-19,Android,2014-01-19,0.0,1,False,0.0,1
14,4.28,5.0,4.0,1.15,Winterfell,2014-06-28,Android,2014-01-14,20.0,2,False,40.0,0
15,3.40,5.0,5.0,1.00,Astapor,2014-01-16,Android,2014-01-16,0.0,1,True,100.0,1
16,6.74,4.8,3.7,1.02,Winterfell,2014-05-30,iPhone,2014-01-25,9.1,2,False,54.5,1
17,7.27,4.8,4.0,1.00,Winterfell,2014-05-15,iPhone,2014-01-07,0.0,1,False,75.0,1
18,2.72,4.7,4.5,1.00,Astapor,2014-04-13,iPhone,2014-01-10,0.0,1,False,33.3,1
19,5.94,5.0,5.0,1.00,Astapor,2014-03-06,iPhone,2014-01-26,0.0,1,True,100.0,1

In [4]:
float(sum(fullData['churn']))/float(len(fullData))

0.6242

In [10]:
fullData['signup_date'].max()

'2014-01-31'